name: "bluebell"
mode: "dev"
port: 8080
version: "v0.1.0"
log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: ""
  port: 3306
  user: "root"
  password: ""
  dbname: "db01"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: ""
  port: 6379
  password: ""
  db: 1
  pool_size: 100